services:
  - type: web
    name: mylinks
    env: static
    staticPublishPath: .
    buildCommand: ""
    headers:
      - path: /*
        key: Permissions-Policy
        value: identity-credentials-get=(self "https://accounts.google.com")
      - path: /*
        key: Cross-Origin-Opener-Policy
        value: same-origin-allow-popups
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
